package util;

import model.StatistikPutusan;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class ExportTxt {

    public static void exportStatistik(StatistikPutusan statistik) {

        File folder = new File("output");

        if (!folder.exists()) {
            folder.mkdir();
        }

        File file = new File(folder, "statistik_putusan.txt");

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {

            writer.write("==========================================");
            writer.newLine();
            writer.write("      STATISTIK PUTUSAN NARKOTIKA");
            writer.newLine();
            writer.write("==========================================");
            writer.newLine();
            writer.newLine();

            writer.write("Total Putusan             : " + statistik.getTotalPutusan());
            writer.newLine();

            writer.write("Rata-rata Vonis           : " + String.format("%.2f", statistik.getRataRataVonis()) + " bulan");
            writer.newLine();

            writer.write("Rata-rata Denda           : Rp" + String.format("%,.0f", statistik.getRataRataDenda()));
            writer.newLine();

            writer.write("Jenis Narkotika Terbanyak : " + statistik.getJenisNarkotikaTerbanyak());
            writer.newLine();
            writer.newLine();

            writer.write("==========================================");
            writer.newLine();
            writer.write("Generated by KMS Putusan Narkotika");
            writer.newLine();
            writer.write("==========================================");

        } catch (IOException e) {
            System.out.println("Gagal export statistik: " + e.getMessage());
        }

    }

}